version: 0.2

phases:
  install:
    commands:
      - apt update && apt install -y python3-dev python3-pip
      - pip3 install awscli
      - npm install
  pre_build:
    commands:
#      - npm test
      - echo "Nothing to do with pre_build phase"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "Nothing to do with post_build phase"